#!/bin/csh -f
# Shell script to run accrete5e and name output properly

# Running this file will currently run through all steps of analysis except 
# plotting.
# If any argument is used after ./run, you are able to change the default input file.
# e.g.: ./run -c

if($# > 0) then
 python mkinput.py -c
else 
 python mkinput.py
endif
echo 'Input created'

# Run script to create input file from GUI
python convert.py
echo 'Jacobson files converted to normal output'

# Run main program

gfortran accrete5e_for_nick.f
mv a.out accrete5e_for_nick
echo 'Program compiled'
./accrete5e_for_nick

# Set string with timestamp

###DEPRICATED###
# Originally I let this script pull variables from the input file to identify
# the runs, but now I just include the input file for complete identification.

# Set string with value for ifol, the followed particle's number
#set num = `cut -d ',' -f10 -s accrete4.inp | cut -d '=' -f2`
# Set string with value for FF
#set ff = `cut -d ',' -f2 -s accrete4.inp | cut -d '=' -f2`
################

set dat = `date +"%Y-%m-%d_%T"`

# Use string 'dat' to create a timestamped folder, identifying the run
#set ful = "run_$dat,particle_$num,FF_$ff"
set ful = "run_$dat"
mkdir data/$ful

# Move all produced .dat files to the new folder, and then the .inp file
find *.dat -not -name output.dat -print0 | xargs -0 mv -t data/$ful
mv accrete4.inp data/$ful
echo 'Final data files stored in' data/$ful

# Run script to create graphical output
#python accplot.py


